<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Images\normal.png" />
    <Resource Include="Images\laugh.png" />
    <Resource Include="Images\angry.png" />
    <Resource Include="Images\cry.png" />
  </ItemGroup>

</Project>
